base/blueprints/sync.py
# -*- coding: utf-8 -*-
"""

"""
import json
import os
import threading

import requests
from flask import (Blueprint, jsonify, abort, redirect, render_template, url_for, current_app, send_from_directory,
                   request)

from base.decorators import permission_required
from base.global_var import sync_threads
from base.utils.dir_status import (create_id, get_path_uuid, files_in_dir, calculate_checksum, sub_dirs)

sync_bp = Blueprint('sync', __name__)

server_url = 'https://sunjingyu.com:8010'

# server_url = 'http://127.0.0.1:5000'

allowed_suffix_dict = {
    'abaqus': ['.project_msg', '.inp', '.for', '.FOR', '.json', '.abaqus_msg', '.job_msg', '.uuid'],
    'abaqus_template': ['.inp', '.for', '.FOR', '.json', '.template_msg', '.job_msg', '.uuid'],
    'abaqus_pre': ['.inp', '.for', '.FOR', '.py', '.json', '.preproc_msg', '.uuid'],
    'virtual': ['.inp', '.for', '.json', '.abaqus_msg', '.job_msg', '.uuid'],
    'experiment': ['.*'],
    'doc': ['.*'],
    'sheet': ['.*'],
    'packing_models': ['.*'],
    'material': ['.*'],
    'pyfem': ['.toml', '.inp', '.msh', '.json', '.project_msg', '.job_msg', '.uuid']
}


def get_module_path_dict():
    module_path_dict = {
        'abaqus': current_app.config['ABAQUS_PATH'],
        'abaqus_template': current_app.config['ABAQUS_TEMPLATE_PATH'],
        'abaqus_pre': current_app.config['ABAQUS_PRE_PATH'],
        'virtual': current_app.config['VIRTUAL_PATH'],
        'experiment': current_app.config['EXPERIMENT_PATH'],
        'doc': current_app.config['DOC_PATH'],
        'material': current_app.config['MATERIAL_PATH'],
        'sheet': current_app.config['SHEET_PATH'],
        'packing_models': current_app.config['PACKING_MODELS_PATH'],
        'pyfem': current_app.config['PYFEM_PATH']
    }
    return module_path_dict


def save_files(module, module_id, module_path_dict, resource_dict, status):
    status['status'] = 'loading'
    module_path = module_path_dict[module]
    if not os.path.exists(module_path):
        os.mkdir(module_path)
    save_path = os.path.join(module_path, str(module_id))
    if not os.path.exists(save_path):
        os.mkdir(save_path)
    for directory in resource_dict['data']:
        if not os.path.exists(os.path.join(save_path, directory)):
            os.mkdir(os.path.join(save_path, directory))
        for url in resource_dict['data'][directory]:
            filename = resource_dict['data'][directory][url][0]
            file_md5 = resource_dict['data'][directory][url][1]
            file_local = os.path.join(save_path, directory, filename)
            if os.path.exists(file_local) and calculate_checksum(file_local) == file_md5:
                status[url] = 'existed'
            else:
                response = requests.get(url)
                with open(file_local, 'wb') as file:
                    file.write(response.content)
                status[url] = 'downloaded'
    status['status'] = 'done'


@sync_bp.route('/', methods=['GET', 'POST'])
@permission_required('RESOURCE')
def index():
    if request.method == 'POST':
        data = request.form.to_dict()
        if 'create_value' in data.keys():
            create_list = [sub_module for sub_module in data['create_value'].split(',') if sub_module != '']
            print(create_list)
        return redirect(url_for('sync.index'))
    return render_template('sync/index.html')


@sync_bp.route('/resource/<module>/<module_id>', methods=['GET', 'POST'])
def resource(module, module_id):
    module_path_dict = get_module_path_dict()
    module_resource = {'module': module, 'module_id': module_id, 'data': {}}

    if module in module_path_dict:
        module_path = module_path_dict[module]
    else:
        return jsonify(None)

    sub_module_path = os.path.join(module_path, module_id)

    if os.path.exists(sub_module_path):
        module_resource['data']['.'] = {}
        for file_dict in files_in_dir(sub_module_path):
            suffix = os.path.splitext(file_dict['name'])[1]
            if suffix == '':  # 如果文件名为空，例如 .uuid 的情况
                suffix = os.path.splitext(file_dict['name'])[0]
            if suffix in allowed_suffix_dict[module] or '.*' in allowed_suffix_dict[module]:
                url = server_url + f"/sync/get_file?module={module}&module_id={module_id}&filename={file_dict['name']}"
                file_path = os.path.join(sub_module_path, file_dict['name'])
                module_resource['data']['.'][url] = [file_dict['name'], calculate_checksum(file_path)]

        for sub_dir in sub_dirs(sub_module_path):
            module_resource['data'][sub_dir] = {}
            for file_dict in files_in_dir(os.path.join(sub_module_path, sub_dir)):
                suffix = os.path.splitext(file_dict['name'])[1]
                if suffix == '':  # 如果文件名为空，例如 .uuid 的情况
                    suffix = os.path.splitext(file_dict['name'])[0]
                if suffix in allowed_suffix_dict[module] or '.*' in allowed_suffix_dict[module]:
                    url = server_url + f"/sync/get_file?module={module}&module_id={module_id}&sub_module_id={sub_dir}&filename={file_dict['name']}"
                    file_path = os.path.join(sub_module_path, sub_dir, file_dict['name'])
                    module_resource['data'][sub_dir][url] = [file_dict['name'], calculate_checksum(file_path)]
        return jsonify(module_resource)
    else:
        return jsonify(None)


@sync_bp.route('/download/<module>/<server_module_id>/to/<local_module_id>', methods=['GET', 'POST'])
def download(module, server_module_id, local_module_id):
    module_path_dict = get_module_path_dict()
    if module in module_path_dict:
        module_path = module_path_dict[module]
    else:
        abort(404)

    url = server_url + f'/sync/resource/{module}/{server_module_id}'
    try:
        response = requests.get(url, timeout=10)
    except requests.exceptions.Timeout:
        abort(408)
    except requests.exceptions.RequestException as e:
        abort(500)

    resource_dict = json.loads(response.text)

    if int(local_module_id) == 0:
        local_module_id = create_id(module_path)

    thread_name = f'{module}/{server_module_id}/{local_module_id}'

    if thread_name not in sync_threads:
        sync_threads[thread_name] = {}
        status = sync_threads[thread_name]
        status['status'] = 'submitted'
        args = (module, local_module_id, module_path_dict, resource_dict, status)
        thread = threading.Thread(target=save_files, args=args)
        thread.start()
    else:
        if sync_threads[thread_name]['status'] == 'done':
            sync_threads.pop(thread_name)
            sync_threads[thread_name] = {}
            status = sync_threads[thread_name]
            status['status'] = 'submitted'
            args = (module, local_module_id, module_path_dict, resource_dict, status)
            thread = threading.Thread(target=save_files, args=args)
            thread.start()

    return render_template('sync/download.html', module=module, server_module_id=server_module_id,
                           local_module_id=local_module_id)


@sync_bp.route('/create/<module>/<server_module_id>', methods=['GET', 'POST'])
def create(module, server_module_id):
    module_path_dict = get_module_path_dict()
    if module in module_path_dict:
        module_path = module_path_dict[module]
    else:
        abort(404)
    local_module_id = create_id(module_path)
    return redirect(
        url_for('.download', module=module, server_module_id=server_module_id, local_module_id=local_module_id))


@sync_bp.route('/download_status/<module>/<server_module_id>/to/<local_module_id>', methods=['GET', 'POST'])
def download_status(module, server_module_id, local_module_id):
    thread_name = f'{module}/{server_module_id}/{local_module_id}'
    if thread_name in sync_threads:
        return jsonify(sync_threads[thread_name])
    else:
        return jsonify(None)


@sync_bp.route('/get_file', methods=['GET', 'POST'])
def get_file():
    module_path_dict = get_module_path_dict()
    module = request.args.get('module')
    module_id = request.args.get('module_id')
    sub_module_id = request.args.get('sub_module_id')
    filename = request.args.get('filename')

    if module in module_path_dict:
        if sub_module_id:
            path = os.path.join(module_path_dict[module], module_id, sub_module_id)
        elif module_id:
            path = os.path.join(module_path_dict[module], module_id)
        else:
            path = ''
    else:
        path = ''

    return send_from_directory(path, filename)


@sync_bp.route('/uuid', methods=['GET', 'POST'])
def uuid():
    local_uuid = get_path_uuid(current_app.config['FILE_PATH'])
    return jsonify(sorted(local_uuid))


@sync_bp.route('/get_server_uuid', methods=['GET', 'POST'])
def get_server_uuid():
    server_uuid_url = server_url + '/sync/uuid'
    response = requests.get(server_uuid_url)
    server_uuid = json.loads(response.text)
    return jsonify(server_uuid)


@sync_bp.route('/get_server_resource/<module>/<module_id>', methods=['GET', 'POST'])
def get_server_resource(module, module_id):
    server_resource_url = server_url + f'/sync/resource/{module}/{module_id}'
    response = requests.get(server_resource_url)
    server_resource = json.loads(response.text)
    return jsonify(server_resource)


@sync_bp.route('/url', methods=['GET', 'POST'])
def url():
    return render_template('sync/url.html')

base/templates/sync/download.html
{% extends 'layout.html' %}
{% from 'bootstrap4/form.html' import render_form, render_form_row, render_field %}

{% block title %}服务器数据同步{% endblock title %}

{% block css %}
{% endblock css %}

{% block pageheader %}子模块同步{% endblock pageheader %}

{% block level %}
<li class="breadcrumb-item"><a href="/">主界面</a></li>
<li class="breadcrumb-item active"><a href="{{ url_for('sync.index') }}">服务器数据同步</a></li>
<li class="breadcrumb-item active">子模块同步</li>
{% endblock level %}

{% block content %}
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">服务器./{{ module }}/{{ server_module_id }}到本地./{{ module }}/{{ local_module_id }}</h3>
          </div>
          <div class="card-body">
            <table class="table table-sm table-hover">
              <thead>
              <tr>
                <th>文件</th>
                <th>状态</th>
              </tr>
              </thead>
              <tbody id="table_sync">
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

{% block script %}
<script type="text/javascript">

  const local_uuid_url = "{{ url_for('sync.uuid') }}";
  const server_uuid_url = "{{ url_for('sync.get_server_uuid') }}";
  const download_status_url = "{{ url_for('sync.download_status', module=module, server_module_id=server_module_id, local_module_id=local_module_id) }}";
  const resource_url = "{{ url_for('sync.get_server_resource', module=module, module_id=server_module_id) }}";

  const request0 = $.get(local_uuid_url);
  const request1 = $.get(server_uuid_url);
  const request2 = $.get(download_status_url);
  const request3 = $.get(resource_url);

  // 使用Promise.all()处理请求
  Promise.all([request0, request1, request2, request3])
    .then(function (results) {
      // 获取请求的结果
      const local_uuid = results[0];
      const server_uuid = results[1];
      const download_status = results[2];
      const resource = results[3];
      // 处理请求的结果
      update_table(local_uuid, server_uuid, download_status, resource)
    })
    .catch(function (error) {
      // 处理错误
      console.log("发生错误:", error);
      alert("发生错误: 远程服务器无响应" + error['status'] + " " + error['statusText'])
    });

  function update_table(local_uuid, server_uuid, download_status, resource) {
    $("#table_sync").empty();
    const tbody = document.getElementById('table_sync');
    for (let sub_module_id in resource['data']) {
      for (let urlStr in resource['data'][sub_module_id]) {
        let filename = resource['data'][sub_module_id][urlStr][0];

        const tr = document.createElement('tr');
        tbody.appendChild(tr);

        let td = document.createElement('td');
        td.innerHTML = sub_module_id + '/' + filename;
        tr.appendChild(td);

        td = document.createElement('td');
        td.setAttribute('id', urlStr);
        if (download_status[urlStr] === 'existed' || download_status[urlStr] === 'downloaded') {
          td.innerHTML = "<i class='fas fa-check-circle' style='color: limegreen;'></i>";
        } else {
          td.innerHTML = "<i class='fas fa-spinner fa-spin' style='color: limegreen;'></i>";
        }
        tr.appendChild(td);
      }
    }
  }

  const refreshID = setInterval(function () {
    $.get(download_status_url, function (download_status) {
      let is_fresh = true
      if (download_status['status'] === 'done') {
        is_fresh = false
      }
      const tdList = document.getElementsByTagName('td');
      const tdIds = [];

      for (let i = 0; i < tdList.length; i++) {
        const td = tdList[i];
        const id = td.getAttribute('id');

        if (id !== null) {
          tdIds.push(id);
        }
      }
      for (urlStr of tdIds) {
        const td = document.getElementById(urlStr);
        if (download_status[urlStr] === 'existed' || download_status[urlStr] === 'downloaded') {
          td.innerHTML = "<i class='fas fa-check-circle' style='color: limegreen;'></i>";
        } else {
          td.innerHTML = "<i class='fas fa-spinner fa-spin' style='color: limegreen;'></i>";
        }
      }
      if (is_fresh === false) {
        clearInterval(refreshID)
      }
    })
  }, 2000);

  // https://blog.csdn.net/weixin_43235307/article/details/121795990
  $(document).on('click', '.checkAll', function () {
    $('.checkOne').prop('checked', $(this).prop('checked'));
  });

  $(document).on('click', '.checkOne', function () {
    var flag = $('.checkOne:checked').length == $('.checkOne').length;
    $('.checkAll').prop('checked', flag);
  });

  document.getElementById("monitor").className = "nav-item menu-open"
  document.getElementById("sync").className = "nav-link active"

</script>
{% endblock script %}

base/templates/sync/index.html
{% extends 'layout.html' %}
{% from 'bootstrap4/form.html' import render_form, render_form_row, render_field %}

{% block title %}服务器数据同步{% endblock title %}

{% block css %}
{% endblock css %}

{% block pageheader %}服务器数据同步{% endblock pageheader %}

{% block level %}
<li class="breadcrumb-item"><a href="/">主界面</a></li>
<li class="breadcrumb-item active">服务器数据同步</li>
{% endblock level %}

{% block content %}
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-6">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">数据同步列表</h3>
          </div>
          <div class="card-body">
            <table class="table table-sm table-hover">
              <thead>
              <tr>
<!--                <th><input type="checkbox" id="customCheck1" class="checkAll1"></th>-->
                <th>服务器模块</th>
                <th></th>
                <th>本地模块</th>
              </tr>
              </thead>
              <tbody id="tableSync1">
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="col-6">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">从服务器创建</h3>
          </div>
          <div class="card-body">
<!--            <button class="btn btn-success" type="submit" id="submit_create">-->
<!--              <i class="fa fa-download"></i>-->
<!--              <strong>批量创建</strong>-->
<!--            </button>-->
<!--            <hr>-->
            <table class="table table-sm table-hover">
              <thead>
              <tr>
<!--                <th><input type="checkbox" id="customCheck2" class="checkAll2"></th>-->
                <th>服务器模块</th>
                <th>下载</th>
              </tr>
              </thead>
              <tbody id="tableSync2">
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

{% block script %}
<script type="text/javascript">

  const local_uuid_url = "{{ url_for('sync.uuid') }}";
  const server_uuid_url = "{{ url_for('sync.get_server_uuid') }}";
  const request1 = $.get(local_uuid_url);
  const request2 = $.get(server_uuid_url);

  // 使用Promise.all()处理请求
  Promise.all([request1, request2])
    .then(function (results) {
      // 获取请求的结果
      const local_uuid = results[0];
      const server_uuid = results[1];
      // 处理请求的结果
      update_table(local_uuid, server_uuid)
    })
    .catch(function (error) {
      // 处理错误
      console.log("发生错误:", error);
      alert("发生错误: 远程服务器无响应" + error['status'] + " " + error['statusText'])
    });

  function update_table(local_uuid, server_uuid) {
    $("#tableSync1").empty();
    const tbody1 = document.getElementById('tableSync1');
    for (const lu of local_uuid) {
      for (const su of server_uuid) {
        if (lu[2] === su[2]) {
          let id = 0;

          const tr = document.createElement('tr');
          tbody1.appendChild(tr);

          let td = document.createElement('td');
          // td.innerHTML = '<input type="checkbox" class="checkOne1" id="' + id++ + '">';
          // tr.appendChild(td);
          //
          // td = document.createElement('td');
          td.innerHTML = su[0] + '/' + su[1];
          tr.appendChild(td);

          td = document.createElement('td');
          // td.innerHTML = "<i class='fas fa-link'></i>";
          let downloadHref = "<a href='download/" + lu[0] + "/" + su[1] + "/to/" + lu[1] + "'>"
          td.innerHTML = downloadHref + "<i class='fas fa-sync'></i></a>";
          tr.appendChild(td);

          td = document.createElement('td');
          td.innerHTML = lu[0] + '/' + lu[1];
          tr.appendChild(td);
        }
      }
    }

    $("#tableSync2").empty();
    const tbody2 = document.getElementById('tableSync2');
    let id = 0;
    for (const su of server_uuid) {
      const tr = document.createElement('tr');
      tbody2.appendChild(tr);

      let td = document.createElement('td');
      // td.innerHTML = '<input type="checkbox" class="checkOne2" id="' + su[0] + "/" + su[1] + '">';
      // tr.appendChild(td);
      //
      // td = document.createElement('td');
      td.innerHTML = su[0] + '/' + su[1];
      tr.appendChild(td);

      td = document.createElement('td');
      let downloadHref = "<a href='create/" + su[0] + "/" + su[1] + "'>"
      td.innerHTML = downloadHref + "<i class='fas fa-download'></i></a>";
      tr.appendChild(td);
    }
  }

  $(document).ready(function () {
    $('#submit_create').on('click', function () {
      const checked_item = $('.checkOne2:checked');
      const checked_items = [];
      for (let i = 0; i < checked_item.length; i++) {
        checked_items.push(checked_item[i].id);
      }
      $.get("create/experiment/1")
      $.get(local_uuid_url, function (local_uuid) {
        $.get(server_uuid_url, function (server_uuid) {
          console.log(local_uuid, server_uuid)
          update_table(local_uuid, server_uuid)
        })
      })
    });
  });

  // const refreshID = setInterval(function () {
  //   $.get(local_uuid_url, function (local_uuid) {
  //     $.get(server_uuid_url, function (server_uuid) {
  //       console.log(local_uuid, server_uuid)
  //       update_table(local_uuid, server_uuid)
  //     })
  //   })
  // }, 2000);

  // https://blog.csdn.net/weixin_43235307/article/details/121795990
  $(document).on('click', '.checkAll1', function () {
    $('.checkOne1').prop('checked', $(this).prop('checked'));
  });

  $(document).on('click', '.checkOne1', function () {
    const flag = $('.checkOne1:checked').length === $('.checkOne1').length;
    $('.checkAll1').prop('checked', flag);
  });

  $(document).on('click', '.checkAll2', function () {
    $('.checkOne2').prop('checked', $(this).prop('checked'));
  });

  $(document).on('click', '.checkOne2', function () {
    const flag = $('.checkOne2:checked').length === $('.checkOne2').length;
    $('.checkAll2').prop('checked', flag);
  });

  document.getElementById("resource").className = "nav-item menu-open"
  document.getElementById("sync").className = "nav-link active"

</script>
{% endblock script %}

base/templates/sync/url.html
{% extends 'layout.html' %}
{% from 'bootstrap4/form.html' import render_form, render_form_row, render_field %}

{% block title %}本地服务器URL{% endblock title %}

{% block css %}
{% endblock css %}

{% block pageheader %}本地服务器URL{% endblock pageheader %}

{% block level %}
<li class="breadcrumb-item"><a href="/">主界面</a></li>
<li class="breadcrumb-item active">本地服务器URL</li>
{% endblock level %}

{% block content %}
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">本地服务器URL</h3>
          </div>
          <div class="card-body">
            <p id="current-url"></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

{% block script %}
<script type="text/javascript">

  document.getElementById("current-url").innerText = window.location.href;
  document.getElementById("resource").className = "nav-item menu-open"
  document.getElementById("url").className = "nav-link active"

</script>
{% endblock script %}