base/forms/virtual.py
# -*- coding: utf-8 -*-
"""

"""
from flask import (current_app)
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired
from wtforms import (IntegerField, SelectField, StringField, SubmitField, TextAreaField)
from wtforms.validators import (DataRequired, Length, NumberRange)

from base.utils.dir_status import (templates_detail)


class UploadForm(FlaskForm):
    filename = FileField('上传文件', validators=[FileRequired()])
    submit = SubmitField('上传')


class VirtualForm(FlaskForm):
    name = StringField('项目名称', validators=[DataRequired(), Length(1, 62)])
    template = SelectField('选择模板', coerce=str)
    descript = TextAreaField('项目描述', render_kw={'rows': 12})
    job = StringField('缺省算例名', default='Job-1', validators=[DataRequired(), Length(1, 126)])
    user = StringField('缺省user文件', default='user.for')
    cpus = IntegerField('缺省算例使用CPU核心数量', default=1, validators=[DataRequired(), NumberRange(1, 16)])
    submit = SubmitField('提交')

    def __init__(self, *args, **kwargs):
        super(VirtualForm, self).__init__(*args, **kwargs)

        templates_path = current_app.config['ABAQUS_TEMPLATE_PATH']
        template_dict = templates_detail(templates_path)
        template_list = []
        for template in template_dict['data']:
            template_list.append('%s_%s' % (template['template_id'], template['name']))

        self.template.choices = template_list


class ParameterForm(FlaskForm):
    para = TextAreaField('parameters.inp')
    submit = SubmitField('保存')

base/blueprints/virtual.py
# -*- coding: utf-8 -*-
"""

"""
import os
import shutil
import uuid

from flask import (abort, Blueprint, current_app, flash, jsonify, redirect, render_template, url_for, send_from_directory, request)
from flask_login import current_user

from base.decorators import permission_required
from base.forms.virtual import (VirtualForm, ParameterForm)
from base.utils.abaqus.Postproc import Postproc
from base.utils.abaqus.Solver import Solver
from base.utils.common import make_dir, dump_json, load_json
from base.utils.dir_status import (create_id, virtuals_detail, get_virtual_status, files_in_dir)

virtual_bp = Blueprint('virtual', __name__)


@virtual_bp.route('/manage_virtuals', methods=['GET', 'POST'])
@permission_required('VIRTUAL')
def manage_virtuals():
    return render_template('virtual/manage_virtuals.html')


@virtual_bp.route('/create_virtual', methods=['GET', 'POST'])
@permission_required('VIRTUAL')
def create_virtual():
    form = VirtualForm()

    if form.validate_on_submit():
        virtuals_path = current_app.config['VIRTUAL_PATH']
        virtual_id = create_id(virtuals_path)
        virtual_path = os.path.join(virtuals_path, str(virtual_id))
        make_dir(virtual_path)
        uuid_file = os.path.join(virtual_path, '.uuid')
        with open(uuid_file, 'w', encoding='utf-8') as f:
            f.write(str(uuid.uuid4()))
        message = {
            'name': form.name.data,
            'template': form.template.data,
            'descript': form.descript.data,
            'job': form.job.data,
            'user': form.user.data,
            'cpus': form.cpus.data
        }
        msg_file = os.path.join(virtual_path, '.virtual_msg')
        dump_json(msg_file, message)
        flash('项目创建成功。', 'success')

        template_id = int(form.template.data.split('_')[0])
        templates_path = current_app.config['ABAQUS_TEMPLATE_PATH']
        template_path = os.path.join(templates_path, str(template_id))
        files = files_in_dir(template_path)
        for file in files:
            shutil.copy(os.path.join(template_path, file['name']),
                        os.path.join(virtual_path, file['name']))
            flash('从模板导入文件%s成功。' % file['name'], 'success')

        return redirect(url_for('.view_virtual', virtual_id=virtual_id))

    return render_template('virtual/create_virtual.html', form=form)


@virtual_bp.route('/edit_virtual/<int:virtual_id>', methods=['GET', 'POST'])
@permission_required('VIRTUAL')
def edit_virtual(virtual_id):
    form = VirtualForm()
    virtuals_path = current_app.config['VIRTUAL_PATH']
    virtual_path = os.path.join(virtuals_path, str(virtual_id))
    msg_file = os.path.join(virtual_path, '.virtual_msg')

    if form.validate_on_submit():
        message = {
            'name': form.name.data,
            'template': form.template.data,
            'descript': form.descript.data,
            'job': form.job.data,
            'user': form.user.data,
            'cpus': form.cpus.data
        }
        dump_json(msg_file, message)
        return redirect(url_for('.view_virtual', project_id=virtual_id))

    message = load_json(msg_file)
    form.name.data = message['name']
    form.template.data = message['template']
    form.descript.data = message['descript']
    form.job.data = message['job']
    form.user.data = message['user']
    form.cpus.data = message['cpus']
    return render_template('virtual/create_virtual.html', form=form)


@virtual_bp.route('/view_virtual/<int:virtual_id>', methods=['GET', 'POST'])
@permission_required('VIRTUAL')
def view_virtual(virtual_id):
    virtuals_path = current_app.config['VIRTUAL_PATH']
    virtual_path = os.path.join(virtuals_path, str(virtual_id))
    msg_file = os.path.join(virtual_path, '.virtual_msg')

    if os.path.exists(virtual_path):
        s = Solver(virtual_path)
        s.read_msg()
        sta = s.get_sta()
        logs = s.get_log()
        run_logs = s.get_run_log()
        para = s.get_parameters()

        form = ParameterForm()
        if form.validate_on_submit():
            para = form.para.data
            s.save_parameters(para)
            flash('parameters.inp保存成功。', 'success')
            return redirect(url_for('.view_virtual', project_id=virtual_id))
        form.para.data = para

        s.parameters_to_json()
        files = files_in_dir(virtual_path)
        solver_status = s.solver_status()

        status = get_virtual_status(virtuals_path, virtual_id)
        files = files_in_dir(virtual_path)
        return render_template('virtual/view_virtual.html', virtual_id=virtual_id, form=form, status=status, files=files, solver_status=solver_status)
    else:
        abort(404)


@virtual_bp.route('/delete_virtual/<int:virtual_id>')
@permission_required('VIRTUAL')
def delete_virtual(virtual_id):
    virtuals_path = current_app.config['VIRTUAL_PATH']
    virtual_path = os.path.join(virtuals_path, str(virtual_id))
    if not current_user.can('MODERATE'):
        flash('您的权限不能删除该项目！', 'warning')
        return redirect(url_for('.manage_virtuals'))
    if os.path.exists(virtual_path):
        shutil.rmtree(virtual_path)
        flash('ABAQUS项目%s删除成功。' % virtual_id, 'success')
    else:
        flash('ABAQUS项目%s不存在。' % virtual_id, 'warning')
    return redirect(url_for('.manage_virtuals'))


@virtual_bp.route('/virtuals_status')
@permission_required('VIRTUAL')
def virtuals_status():
    data = virtuals_detail(current_app.config['VIRTUAL_PATH'])
    return jsonify(data)


@virtual_bp.route('/get_virtual_file/<int:virtual_id>/<path:filename>')
@permission_required('VIRTUAL')
def get_virtual_file(virtual_id, filename):
    return send_from_directory(os.path.join(current_app.config['VIRTUAL_PATH'], str(virtual_id)), filename)


@virtual_bp.route('/run_virtual/<int:virtual_id>')
@permission_required('VIRTUAL')
def run_virtual(virtual_id):
    virtuals_path = current_app.config['VIRTUAL_PATH']
    virtual_path = os.path.join(virtuals_path, str(virtual_id))
    if os.path.exists(virtual_path):
        s = Solver(virtual_path)
        s.read_msg()
        s.clear()
        if s.check_files():
            proc = s.run()
            with open(os.path.join(virtual_path, '.solver_status'), 'w', encoding='utf-8') as f:
                f.write('Submitting')
        else:
            flash('缺少必要的计算文件。', 'warning')
        return redirect(request.referrer or url_for('.view_virtual', virtual_id=virtual_id))
    else:
        abort(404)


@virtual_bp.route('/terminate_virtual/<int:virtual_id>')
@permission_required('VIRTUAL')
def terminate_virtual(virtual_id):
    virtuals_path = current_app.config['VIRTUAL_PATH']
    virtual_path = os.path.join(virtuals_path, str(virtual_id))
    if os.path.exists(virtual_path):
        s = Solver(virtual_path)
        s.read_msg()
        proc = s.terminate()
        with open(os.path.join(virtual_path, '.solver_status'), 'w', encoding='utf-8') as f:
            f.write('Stopping')
        return redirect(request.referrer or url_for('.view_virtual', virtual_id=virtual_id))
    else:
        abort(404)


@virtual_bp.route('/prescan_odb/<int:virtual_id>')
@permission_required('VIRTUAL')
def prescan_odb(virtual_id):
    virtuals_path = current_app.config['VIRTUAL_PATH']
    virtual_path = os.path.join(virtuals_path, str(virtual_id))
    if os.path.exists(virtual_path):
        p = Postproc(virtual_path)
        p.read_msg()
        if p.has_odb():
            proc = p.prescan_odb()
            with open(os.path.join(virtual_path, '.prescan_status'), 'w', encoding='utf-8') as f:
                f.write('Submitting')
        else:
            flash('缺少odb文件。', 'warning')
        return redirect(request.referrer or url_for('.view_virtual', virtual_id=virtual_id))
    else:
        abort(404)


@virtual_bp.route('/odb_to_npz/<int:virtual_id>')
@permission_required('VIRTUAL')
def odb_to_npz(virtual_id):
    virtuals_path = current_app.config['VIRTUAL_PATH']
    virtual_path = os.path.join(virtuals_path, str(virtual_id))
    if os.path.exists(virtual_path):
        p = Postproc(virtual_path)
        p.read_msg()
        if p.has_odb() and p.check_setting_files():
            proc = p.odb_to_npz()
            with open(os.path.join(virtual_path, '.odb_to_npz_status'), 'w', encoding='utf-8') as f:
                f.write('Submitting')
            with open(os.path.join(virtual_path, '.odb_to_npz_proc'), 'w', encoding='utf-8') as f:
                f.write('0.0\n')
        else:
            flash('缺少odb文件或odb_to_npz.json配置文件。', 'warning')
        return redirect(request.referrer or url_for('.view_virtual', virtual_id=virtual_id))
    else:
        abort(404)


@virtual_bp.route('/print_figure/<int:virtual_id>', methods=['GET', 'POST'])
@permission_required('VIRTUAL')
def print_figure(virtual_id):
    virtuals_path = current_app.config['VIRTUAL_PATH']
    virtual_path = os.path.join(virtuals_path, str(virtual_id))
    if os.path.exists(virtual_path):
        p = Postproc(virtual_path)
        p.read_msg()
        if p.has_odb():
            proc = p.print_figure()
            with open(os.path.join(virtual_path, '.print_figure_status'), 'w', encoding='utf-8') as f:
                f.write('Submitting')
            return redirect(request.referrer or url_for('.view_virtual', virtual_id=virtual_id))
        else:
            flash('缺少odb文件。', 'warning')
        status = get_virtual_status(virtuals_path, virtual_id)
        logs = p.get_print_figure_log()
        return redirect(request.referrer or url_for('.view_virtual', virtual_id=virtual_id))
    else:
        abort(404)

base/templates/virtual/create_virtual.html
{% extends 'layout.html' %}
{% from 'bootstrap4/form.html' import render_form, render_form_row, render_field %}

{% block title %}新建/编辑虚拟实验{% endblock title %}

{% block pageheader %}新建/编辑虚拟实验{% endblock pageheader %}

{% block level %}
<li class="breadcrumb-item"><a href="/">主界面</a></li>
<li class="breadcrumb-item active">新建/编辑虚拟实验</li>
{% endblock level %}

{% block content %}
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-6">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">虚拟实验配置</h3>
              </div>
              <div class="card-body">
                <form action="" method="post" class="form" role="form">
                  {{ render_form(form) }}
                </form>
              </div>
            </div>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
{% endblock content %}

{% block script %}
<script type="text/javascript">

  document.getElementById("virtual").className = "nav-item menu-open"
  document.getElementById("create_virtual").className = "nav-link active"
  
</script>
{% endblock script %}

base/templates/virtual/manage_virtuals.html
{% extends 'layout.html' %}
{% from 'bootstrap4/form.html' import render_form, render_form_row, render_field %}

{% block title %}虚拟实验管理{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='AdminLTE/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
{% endblock css %}

{% block pageheader %}虚拟实验管理{% endblock pageheader %}

{% block level %}
<li class="breadcrumb-item"><a href="/">主界面</a></li>
<li class="breadcrumb-item active">虚拟实验管理</li>
{% endblock level %}

{% block content %}
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">虚拟实验列表</h3>
              </div>
              <div class="card-body">
                <table id="data" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th width=50px>项目ID</th>
                      <th>项目名称</th>
                      <th width=150px>创建时间</th>
                      <th width=150px>操作</th>
                    </tr>
                  </thead>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock content %}

{% block script %}

<script src="{{ url_for('static', filename='AdminLTE/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ url_for('static', filename='AdminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>

<script type="text/javascript">

  $.fn.dataTable.defaults.oLanguage = {
    "sProcessing": "处理中...",
    "sLengthMenu": "显示 _MENU_ 项结果",
    "sZeroRecords": "没有匹配结果",
    "sInfo": "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
    "sInfoEmpty": "显示第 0 至 0 项结果，共 0 项",
    "sInfoFiltered": "(由 _MAX_ 项结果过滤)",
    "sInfoPostFix": "",
    "sSearch": "搜索：",
    "sUrl": "",
    "sEmptyTable": "表中数据为空",
    "sLoadingRecords": "载入中...",
    "sInfoThousands": ",",
    "oPaginate": {
      "sFirst": "首页",
      "sPrevious": "上页",
      "sNext": "下页",
      "sLast": "末页"
    },
    "oAria": {
      "sSortAscending": ": 以升序排列此列",
      "sSortDescending": ": 以降序排列此列"
    }
  };

  $(function () {
    $('#data').DataTable({
      "paging": true,
      "pageLength": 50,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
      "ajax": "{{ url_for('virtual.virtuals_status') }}",
      "columns": [
          { data: 'virtual_id' },
          { data: 'name' },
          { data: 'virtual_time' },
          { data: 'operation' },
      ],
    });
  });

  document.getElementById("virtual").className = "nav-item menu-open"
  document.getElementById("manage_virtuals").className = "nav-link active"

</script>
{% endblock script %}

base/templates/virtual/view_virtual.html
{% extends 'layout.html' %}
{% from 'bootstrap4/form.html' import render_form, render_form_row, render_field %}

{% block title %}{{ virtual_id }}号虚拟实验{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='AdminLTE/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
{% endblock css %}

{% block pageheader %}虚拟实验信息{% endblock pageheader %}

{% block level %}
<li class="breadcrumb-item"><a href="/">主界面</a></li>
<li class="breadcrumb-item"><a href="{{ url_for('virtual.manage_virtuals') }}">虚拟实验管理</a></li>
<li class="breadcrumb-item active">虚拟实验信息</li>
{% endblock level %}

{% block content %}
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card card-primary" data-card-id="card-1">
              <div class="card-header">
                <h3 class="card-title">{{ virtual_id }}号虚拟实验</h3>
              </div>
              <div class="card-body">
                <div class="row">
                  <div class="col-6">
                    <h5 class="text-primary">轴向应力云图</h5>
                    <img src="{{ url_for('virtual.get_virtual_file', virtual_id=virtual_id, filename='S11.gif') }}" width="100%">
                  </div>
                  <div class="col-6">
                    <h5 class="text-primary">力位移曲线</h5>
                    <img src="{{ url_for('virtual.get_virtual_file', virtual_id=virtual_id, filename='disp-force.png') }}" width="80%">
                  </div>
                  <div class="col-12">
                    <h5 class="text-primary">求解控制</h5>
                    当前状态：{{ solver_status }}
                    <p class="mb-1">您可以通过点击下面的按钮开始、暂停或终止ABAQUS的计算，并通过<a href="javascript:location.reload();">刷新</a>页面获取算例状态。</p>

                    {% if solver_status=='Submitting' or solver_status=='Running' or solver_status=='Pause' or solver_status=='Stopping' %}
                    <button class="btn btn-secondary" disabled="disabled"><strong>计 算</strong></button>
                    {% else %}
                    <a href="{{ url_for('virtual.run_virtual', virtual_id=virtual_id) }}" class="btn btn-success"><strong>计 算</strong></a>
                    {% endif %}

                    {% if solver_status=='Running' %}
                    <a href="#" class="btn btn-warning"><strong>暂 停</strong></a>
                    {% else %}
                    <button class="btn btn-secondary" disabled="disabled"><strong>暂 停</strong></button>
                    {% endif %}

                    {% if solver_status=='Pause' %}
                    <a href="#" class="btn btn-info"><strong>继 续</strong></a>
                    {% else %}
                    <button class="btn btn-secondary" disabled="disabled"><strong>继 续</strong></button>
                    {% endif %}

                    {% if solver_status=='Running' %}
                    <a href="{{ url_for('virtual.terminate_virtual', virtual_id=virtual_id) }}" class="btn btn-danger"><strong>终 止</strong></a>
                    {% else %}
                    <button class="btn btn-secondary" disabled="disabled"><strong>终 止</strong></button>
                    {% endif %}
                    {{ button }}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-6">
            <div class="card card-primary" data-card-id="card-2">
              <div class="card-header">
                <h3 class="card-title">参数文件</h3>
              </div>
              <div class="card-body">
                <div class="row">
                  <div class="col-12">
                    <form action="" method="post" class="form" role="form">
                      {{ form.csrf_token() }}
                      {{ render_field(form.para, style="height: 450px;") }}
                      {{ render_field(form.submit, button_style='btn btn-primary') }}
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-6">
            <div class="card card-primary" data-card-id="card-3">
              <div class="card-header">
                <h3 class="card-title">文件列表</h3>
              </div>
              <div class="card-body">
                <div class="row">
                  <div class="col-12">
                    <h5 class="text-primary">虚拟实验信息</h5>
                    <ul class="list-unstyled">
                      <li> 虚拟实验名称：{{ status['name'] }} </li>
                      <li> 虚拟实验编号：{{ virtual_id }} </li>
                      <li> 虚拟实验模板：{{ status['template'] }} </li>
                      <li> 创建时间：{{ status['virtual_time'] }} </li>
                      <li> 使用CPU核心数量：{{ status['cpus'] }} </li>
                      <li> 虚拟实验备注：</li>
                      <textarea id="descript" class="form-control" rows="4">{{ status['descript'] }}</textarea>
                      <a class='btn btn-primary' href="{{ url_for('virtual.edit_virtual', virtual_id=virtual_id) }}"><strong>编辑信息</strong></a>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-6">
            <div class="card card-primary" data-card-id="card-4">
              <div class="card-header">
                <h3 class="card-title">文件列表</h3>
              </div>
              <div class="card-body">
                <div class="row">
                  <div class="col-12">
                    <table class="table table-sm table-hover">
                      <thead>
                        <tr>
                          <th width=40%>文件名</th>
                          <th width=30%>修改日期</th>
                          <th width=10%>大小</th>
                          <th width=20%>操作</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for file in files %}
                        <tr>
                          <td> {{ file['name'] }} </td>
                          <td> {{ file['time'] }} </td>
                          <td> {{ file['size'] }} </td>
                          <td> <a href="{{ url_for('virtual.get_virtual_file', virtual_id=virtual_id, filename=file['name']) }}" target="_blank">下载</a> </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock content %}

{% block script %}
<script src="{{ url_for('static', filename='AdminLTE/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ url_for('static', filename='AdminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>

<script type="text/javascript">

  $(document).ready(function () {
    $('#descript').attr('disabled', true)
  });

  document.getElementById('virtual').className = 'nav-item menu-open'

</script>
{% endblock script %}