base/forms/flow.py
# -*- coding: utf-8 -*-
"""

"""
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired
from wtforms import (FloatField, IntegerField, SelectField, StringField, SubmitField, TextAreaField, BooleanField, RadioField)
from wtforms.validators import (DataRequired, Length, NumberRange)


class UploadForm(FlaskForm):
    filename = FileField('上传文件', validators=[FileRequired()])
    submit = SubmitField('上传')


class FlowForm(FlaskForm):
    name = StringField('流程名称', validators=[DataRequired(), Length(1, 62)])
    descript = TextAreaField('流程备注', render_kw={'rows': 12})
    submit = SubmitField('提交')


class JobForm(FlaskForm):
    project_id = SelectField('ABAQUS项目编号', coerce=str)
    job_id = IntegerField('需要重写的ABAQUS作业编号', default=1, validators=[DataRequired(), NumberRange(1, 1024 * 1024)])
    overwrite = BooleanField('重写作业（不选则新建作业）')
    job = StringField('算例名', default='Job-1', validators=[DataRequired(), Length(1, 126)])
    user = StringField('算例user文件', default='user.for')
    cpus = IntegerField('CPU数量', default=1, validators=[DataRequired(), NumberRange(1, 64)])
    descript = TextAreaField('算例备注', render_kw={'rows': 2})
    submit = SubmitField('提交')

    def __init__(self, *args, **kwargs):
        super(JobForm, self).__init__(*args, **kwargs)
        self.project_id.choices = ['']


class F1From(FlaskForm):
    tool_option = RadioField('刀具选项', choices=[('analytical', '理想刀具参数建模'), ('file', '从CAD文件导入')], default='analytical', validators=[DataRequired()])
    r1 = FloatField('r1，mm', default=20.0)
    r2 = FloatField('r2，mm', default=25.0)
    n = IntegerField('刀数', default=4, validators=[DataRequired(), NumberRange(4, 8)])
    length = FloatField('长度，mm', default=20.0)
    pitch = FloatField('螺距，mm', default=-60.0)
    tool_ref_point_x = FloatField('参考点x坐标，mm', default=0.0)
    tool_ref_point_y = FloatField('参考点y坐标，mm', default=0.0)
    tool_ref_point_z = FloatField('参考点z坐标，mm', default=0.0)
    step_file_name = SelectField('stp文件名称', coerce=str)
    tool_seed_size = FloatField('铣刀网格尺寸，mm', default=5.0)

    x_length_of_plane = FloatField('x方向长度，mm', default=50.0)
    y_length_of_plane = FloatField('y方向长度，mm', default=50.0)
    z_length_of_plane = FloatField('z方向长度，mm', default=10.0)
    plane_seed_size = FloatField('平面网格尺寸，mm', default=5.0)

    x_shift_of_tool = FloatField('初始x，mm', default=0.0)
    y_shift_of_tool = FloatField('初始y，mm', default=0.0)
    z_shift_of_tool = FloatField('初始z，mm', default=0.0)

    material_tool = SelectField('铣刀材料', coerce=str)
    material_plane = SelectField('平板材料', coerce=str)
    material_interaction = SelectField('接触属性', coerce=str)

    tool_rotation_speed = FloatField('铣刀转速，rpm', default=300.0)
    tool_shift_speed = FloatField('铣刀平移速度，mm/min', default=10.0)

    temperature_tool_z1 = FloatField('铣刀端面温度，℃', default=20.0)
    temperature_tool_init = FloatField('铣刀初始温度，℃', default=20.0)
    temperature_plane_init = FloatField('平板初始温度，℃', default=20.0)

    tool_path_type = RadioField('刀具路径选项', choices=[('square_wave', '方波铣削'), ('drill', '钻孔'), ('tool_path_file', '刀具路径文件')], default='square_wave', validators=[DataRequired()])

    square_wave_width = FloatField('方波宽度，mm', default=30.0)
    square_wave_height = FloatField('方波高度，mm', default=70.0)
    square_wave_depth = FloatField('方波深度，mm', default=5.0)
    square_wave_head_shift = FloatField('头部平移量', default=0.0, validators=[NumberRange(0.0, 1.0)])
    square_wave_tail_shift = FloatField('尾部平移量', default=0.0, validators=[NumberRange(0.0, 1.0)])
    square_wave_cycles = IntegerField('面内周期数', default=2, validators=[DataRequired(), NumberRange(1, 10000)])
    square_wave_layers = IntegerField('深度层数', default=1, validators=[DataRequired(), NumberRange(1, 10000)])
    drill_depth = FloatField('钻孔深度，mm', default=10.0)
    tool_path_file_name = SelectField('刀具路径文件', coerce=str)

    output_variables = StringField('输出变量', validators=[DataRequired(), Length(1, 1024)], default='U, RF, S, LE, NT, STATUS')
    output_numIntervals = IntegerField('输出增量步数量', default=20, validators=[DataRequired(), NumberRange(1, 1024)])

    timeIncrementationMethod = SelectField('时间增量步长方法', coerce=str)
    userDefinedInc = FloatField('用户自定义增量步长', default=1.0e-7)
    step_time = FloatField('载荷步时间，s', default=1.0)
    mass_scaling_factor = FloatField('质量缩放系数', default=1.0)

    submit = SubmitField('保存当前参数')

    def __init__(self, *args, **kwargs):
        super(F1From, self).__init__(*args, **kwargs)
        self.step_file_name.choices = ['']
        self.tool_path_file_name.choices = ['']
        self.timeIncrementationMethod.choices = ['AUTO', 'AUTOMATIC_EBE', 'FIXED_USER_DEFINED_INC']
        self.material_tool.choices = ['']
        self.material_plane.choices = ['']
        self.material_interaction.choices = ['']

base/blueprints/flow.py
# -*- coding: utf-8 -*-
"""

"""
import json
import os
import shutil

from flask import (Blueprint, abort, current_app, flash, jsonify, redirect, render_template, request, send_from_directory, url_for)
from flask_login import current_user
from markupsafe import Markup

from base.decorators import permission_required
from base.forms.flow import UploadForm, FlowForm, JobForm, F1From
from base.utils.abaqus.Preproc import Preproc
from base.utils.common import make_dir, dump_json, load_json
from base.utils.dir_status import (create_id, files_in_dir, flows_detail, materials_detail, projects_detail, file_time)

flow_bp = Blueprint('flow', __name__)


@flow_bp.route('/flows_status/')
@permission_required('FLOW')
def flows_status():
    data = flows_detail(current_app.config['FLOW_PATH'])
    return jsonify(data)


@flow_bp.route('/manage_flows/')
@permission_required('FLOW')
def manage_flows():
    return render_template('flow/manage_flows.html')


@flow_bp.route('/edit_flow/<int:flow_id>', methods=['GET', 'POST'])
@permission_required('FLOW')
def edit_flow(flow_id):
    form = FlowForm()
    flows_path = current_app.config['FLOW_PATH']
    flow_path = os.path.join(flows_path, str(flow_id))
    msg_file = os.path.join(flow_path, '.flow_msg')

    if form.validate_on_submit():
        message = {
            'name': form.name.data,
            'descript': form.descript.data
        }
        dump_json(msg_file, message)
        return redirect(url_for('.manage_flows'))

    message = load_json(msg_file)
    form.name.data = message['name']
    form.descript.data = message['descript']
    return render_template('flow/edit_flow.html', form=form)


@flow_bp.route('/get_flow_file/<int:flow_id>/<path:filename>')
@permission_required('FLOW')
def get_flow_file(flow_id, filename):
    return send_from_directory(os.path.join(current_app.config['FLOW_PATH'], str(flow_id)), filename)


@flow_bp.route('/delete_flow_file/<int:flow_id>/<path:filename>')
@permission_required('FLOW')
def delete_flow_file(flow_id, filename):
    flow_path = current_app.config['FLOW_PATH']
    file = os.path.join(flow_path, str(flow_id), str(filename))
    if not current_user.can('MODERATE'):
        flash('您的权限不能删除该文件！', 'warning')
        return redirect(request.referrer)
    if os.path.exists(file):
        os.remove(file)
        flash('文件%s删除成功。' % filename, 'success')
    else:
        flash('文件%s不存在。' % filename, 'warning')
    return redirect(request.referrer)


@flow_bp.route('/run_preproc/<int:flow_id>')
@permission_required('FLOW')
def run_preproc(flow_id):
    flows_path = current_app.config['FLOW_PATH']
    flow_path = os.path.join(flows_path, str(flow_id))
    if os.path.exists(flow_path):
        p = Preproc(flow_path)
        p.read_msg()
        p.clear()
        if p.check_setting_files():
            proc = p.run()
            with open(os.path.join(flow_path, '.preproc_status'), 'w', encoding='utf-8') as f:
                f.write('Submitting')
        else:
            flash(f'缺少{p.script}脚本文件。', 'warning')
        return redirect(request.referrer)
    else:
        abort(404)


@flow_bp.route('/1', methods=['GET', 'POST'])
@permission_required('FLOW')
def f1():
    flow_id = 1
    flows_path = current_app.config['FLOW_PATH']
    flow_path = os.path.join(flows_path, str(flow_id))
    setting_file = os.path.join(flow_path, 'setting.json')
    job_form_message_file = os.path.join(flow_path, '.job_form_msg')

    materials_path = current_app.config['MATERIAL_PATH']
    material_dict = materials_detail(materials_path)
    material_list = []
    for material in material_dict['data']:
        material_list.append('%s_%s' % (material['material_id'], material['name']))

    abaqus_path = current_app.config['ABAQUS_PATH']
    project_dict = projects_detail(abaqus_path)
    project_list = []
    for project in project_dict['data']:
        project_list.append('%s_%s' % (project['project_id'], project['name']))

    files = files_in_dir(flow_path)
    step_file_name_list = []
    tool_path_file_name_list = []
    for file in files:
        if file['name'].endswith('.stp'):
            step_file_name_list.append(file['name'])
        elif file['name'].endswith('.txt'):
            tool_path_file_name_list.append(file['name'])

    upload_form = UploadForm(prefix='upload')
    job_form = JobForm(prefix='job')
    form = F1From()

    form.step_file_name.choices = step_file_name_list
    form.material_tool.choices = material_list
    form.material_plane.choices = material_list
    form.material_interaction.choices = material_list
    form.tool_path_file_name.choices = tool_path_file_name_list

    job_form.project_id.choices = project_list

    if upload_form.submit.data and upload_form.validate():
        f = upload_form.filename.data
        f.save(os.path.join(flow_path, f.filename))
        flash('上传文件%s成功。' % f.filename, 'success')
        return redirect(url_for('flow.f1', flow_id=flow_id, form=form, upload_form=upload_form, job_form=job_form))

    if job_form.submit.data and job_form.validate():
        project_id = job_form.project_id.data.split('_')[0]
        abaqus_path = current_app.config['ABAQUS_PATH']
        project_path = os.path.join(abaqus_path, str(project_id))
        overwrite = job_form.overwrite.data
        if overwrite:
            job_id = job_form.job_id.data
            job_path = os.path.join(project_path, str(job_id))
            if not os.path.exists(job_path):
                flash('不存在ABAQUS作业%s-%s！' % (project_id, job_id), 'danger')
                return redirect(url_for('flow.f1', flow_id=flow_id, form=form, upload_form=upload_form, job_form=job_form))
        else:
            job_id = create_id(project_path)
            job_path = os.path.join(project_path, str(job_id))
            make_dir(job_path)

        job_message = {
            'job': job_form.job.data,
            'user': job_form.user.data,
            'cpus': job_form.cpus.data,
            'descript': job_form.descript.data
        }
        job_message_file = os.path.join(job_path, '.job_msg')
        dump_json(job_message_file, job_message)

        files = files_in_dir(flow_path)
        for file in files:
            shutil.copy(os.path.join(flow_path, file['name']), os.path.join(job_path, file['name']))
        flash(
            Markup('从流程1导出文件到<a href="%s">ABAQUS项目%s-%s</a>成功。') % (
                url_for('abaqus.view_job', project_id=project_id, job_id=job_id), project_id, job_id),
            'success'
        )

        job_form_message = {
            'project_id': job_form.project_id.data,
            'job_id': job_form.job_id.data,
            'overwrite': job_form.overwrite.data,
            'job': job_form.job.data,
            'user': job_form.user.data,
            'cpus': job_form.cpus.data,
            'descript': job_form.descript.data
        }
        dump_json(job_form_message_file, job_form_message)

        return redirect(url_for('flow.f1', flow_id=flow_id, form=form, upload_form=upload_form, job_form=job_form))

    if os.path.exists(job_form_message_file):
        job_form_message = load_json(job_form_message_file)
        job_form.project_id.data = job_form_message['project_id']
        job_form.job_id.data = job_form_message['job_id']
        job_form.overwrite.data = job_form_message['overwrite']
        job_form.job.data = job_form_message['job']
        job_form.user.data = job_form_message['user']
        job_form.cpus.data = job_form_message['cpus']
        job_form.descript.data = job_form_message['descript']

    if form.submit.data and form.validate():
        message = {
            'tool_option': form.tool_option.data,
            'r1': form.r1.data,
            'r2': form.r2.data,
            'n': form.n.data,
            'length': form.length.data,
            'pitch': form.pitch.data,
            'step_file_name': form.step_file_name.data,
            'tool_ref_point_x': form.tool_ref_point_x.data,
            'tool_ref_point_y': form.tool_ref_point_y.data,
            'tool_ref_point_z': form.tool_ref_point_z.data,
            'tool_seed_size': form.tool_seed_size.data,
            'x_length_of_plane': form.x_length_of_plane.data,
            'y_length_of_plane': form.y_length_of_plane.data,
            'z_length_of_plane': form.z_length_of_plane.data,
            'plane_seed_size': form.plane_seed_size.data,
            'x_shift_of_tool': form.x_shift_of_tool.data,
            'y_shift_of_tool': form.y_shift_of_tool.data,
            'z_shift_of_tool': form.z_shift_of_tool.data,
            'material_tool': form.material_tool.data,
            'material_plane': form.material_plane.data,
            'tool_rotation_speed': form.tool_rotation_speed.data,
            'tool_shift_speed': form.tool_shift_speed.data,
            'temperature_tool_z1': form.temperature_tool_z1.data,
            'temperature_tool_init': form.temperature_tool_init.data,
            'temperature_plane_init': form.temperature_plane_init.data,
            'tool_path_type': form.tool_path_type.data,
            'square_wave_width': form.square_wave_width.data,
            'square_wave_height': form.square_wave_height.data,
            'square_wave_depth': form.square_wave_depth.data,
            'square_wave_head_shift': form.square_wave_head_shift.data,
            'square_wave_tail_shift': form.square_wave_tail_shift.data,
            'square_wave_cycles': form.square_wave_cycles.data,
            'square_wave_layers': form.square_wave_layers.data,
            'drill_depth': form.drill_depth.data,
            'tool_path_file_name': form.tool_path_file_name.data,
            'material_interaction': form.material_interaction.data,
            'output_variables': form.output_variables.data,
            'output_numIntervals': form.output_numIntervals.data,
            'timeIncrementationMethod': form.timeIncrementationMethod.data,
            'userDefinedInc': form.userDefinedInc.data,

base/templates/flow/cut.html
{% extends 'layout.html' %}
{% from 'bootstrap4/form.html' import render_form, render_form_row, render_field %}

{% block title %}{{ flow_id }}号流程{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='AdminLTE/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
{% endblock css %}

{% block pageheader %}流程信息{% endblock pageheader %}

{% block level %}
<li class="breadcrumb-item"><a href="/">主界面</a></li>
<li class="breadcrumb-item active">流程信息</li>
{% endblock level %}

{% block content %}
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-6">
            <div class="column">
              <div class="col-12">
                <div class="card card-primary">
                  <div class="card-header">
                    <h3 class="card-title">{{ flow_id }}号流程信息</h3>
                    <div class="card-tools">
                      <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                      </button>
                    </div>
                  </div>
                  <div class="card-body">
                    <div class="row">
                      <div class="col-12">
                        <h5 class="text-primary">流程信息</h5>
                        <ul class="list-unstyled">
                          <li> 流程名称：{{ status['name'] }}</li>
                          <li> 流程编号：{{ flow_id }}</li>
                          <li> 创建时间：{{ status['flow_time'] }}</li>
                          <li> 流程备注：</li>
                          <textarea id="descript" class="form-control" rows="4">{{ status['descript'] }}</textarea>
                        </ul>
                        <h5 class="text-primary">运行控制</h5>
                        <p class="mb-1" id="text_solver_status">{{ solver_status }}</p>
                        <p class="mb-1">您可以通过点击下面的按钮开始ABAQUS前处理的运行。
                        </p>

                        <button id="calculateBtn" class="btn btn-secondary" disabled><strong>开始前处理</strong></button>
                        <a id="calculateLink" href="{{ url_for('flow.run_preproc', flow_id=flow_id) }}" class="btn btn-success"><strong>开始前处理</strong></a>

<!--                        <button id="resetBtn" class="btn btn-secondary" disabled><strong>重 置</strong></button>-->
<!--                        <a id="resetLink" href="#" class="btn btn-info"><strong>重 置</strong></a>-->

                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <form action="" method="post" class="form" role="form">
              {{ form.csrf_token() }}
                <div class="col-12">
                  <div class="card card-info">
                    <div class="card-header">
                      <h3 class="card-title">铣刀零件参数</h3>
                      <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                          <i class="fas fa-minus"></i>
                        </button>
                      </div>
                    </div>
                    <div class="card-body">
                      <div class="row">
                        <div class="col-12">
                          {{ render_form_row([form.r1, form.r2]) }}
                          {{ render_form_row([form.n, form.length]) }}
                          {{ render_form_row([form.pitch, form.tool_seed_size]) }}
                          {{ render_form_row([form.material_tool]) }}
                          {{ render_field(form.submit, button_style='btn btn-info') }}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-12">
                  <div class="card card-info">
                    <div class="card-header">
                      <h3 class="card-title">平板零件参数</h3>
                      <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                          <i class="fas fa-minus"></i>
                        </button>
                      </div>
                    </div>
                    <div class="card-body">
                      <div class="row">
                        <div class="col-12">
                          {{ render_form_row([form.x_length_of_plane, form.y_length_of_plane]) }}
                          {{ render_form_row([form.z_length_of_plane, form.plane_seed_size]) }}
                          {{ render_form_row([form.material_plane]) }}
                          {{ render_field(form.submit, button_style='btn btn-info') }}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-12">
                  <div class="card card-info">
                    <div class="card-header">
                      <h3 class="card-title">铣刀参考点初始位置</h3>
                      <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                          <i class="fas fa-minus"></i>
                        </button>
                      </div>
                    </div>
                    <div class="card-body">
                      <div class="row">
                        <div class="col-12">
                          {{ render_form_row([form.x_shift_of_tool, form.y_shift_of_tool, form.z_shift_of_tool]) }}
                          {{ render_field(form.submit, button_style='btn btn-info') }}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-12">
                  <div class="card card-info">
                    <div class="card-header">
                      <h3 class="card-title">求解控制</h3>
                      <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                          <i class="fas fa-minus"></i>
                        </button>
                      </div>
                    </div>
                    <div class="card-body">
                      <div class="row">
                        <div class="col-12">
                          {{ render_form_row([form.timeIncrementationMethod, form.userDefinedInc]) }}
                          {{ render_field(form.submit, button_style='btn btn-info') }}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </form>
              <div class="col-12">
                <div class="card card-primary collapsed-card">
                  <div class="card-header">
                    <h3 class="card-title">文件列表</h3>
                    <div class="card-tools">
                      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-plus"></i></button>
                    </div>
                  </div>
                  <div class="card-body">
                    <div class="row">
                      <div class="col-12">
                        <h5 class="text-primary">上传文件</h5>
                        <form action="" method="post" class="form" enctype="multipart/form-data" role="form">
                          {{ upload_form.csrf_token }}
                          <div class="form-group">
                            {{ upload_form.submit }}{{ upload_form.filename }}
                          </div>
                        </form>
                      </div>

                      <div class="col-12">
                        <table class="table table-sm table-hover">
                          <thead>
                          <tr>
                            <th width=40%>文件名</th>
                            <th width=30%>修改日期</th>
                            <th width=10%>大小</th>
                            <th width=20%>操作</th>
                          </tr>
                          </thead>
                          <tbody id="table_files_body">
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-6">
            <div class="column">
              <div class="col-12">
                <div class="card">
                  <div class="card-header d-flex p-0">
                    <h3 class="card-title p-3">前处理状态</h3>
                    <ul class="nav nav-pills ml-auto p-2">
                      <li class="nav-item"><a class="nav-link active" href="#tab_1" data-toggle="tab">前处理日志 abaqus.rpy</a></li>
                      <li class="nav-item"><a class="nav-link" href="#tab_2" data-toggle="tab">命令行日志 run.log</a></li>
                    </ul>
                  </div>
                  <div class="card-body">
                    <div class="tab-content">
                      <div class="tab-pane active" id="tab_1">
                        <textarea id="textarea_log" class="form-control" style="height: 711.5px;"></textarea>
                      </div>
                      <div class="tab-pane" id="tab_2">
                        <textarea id="textarea_run_log" class="form-control" style="height: 711.5px;"></textarea>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock content %}

{% block script %}
<script type="text/javascript">

  $(document).ready(function () {
    $('#descript').attr('disabled', true)
  });
  
  document.getElementById('abaqus').className = 'nav-item menu-open'

  let isUpdate = true

  function updateFiles(files) {
    const tableBody = document.getElementById('table_files_body');
    tableBody.innerHTML = "";
    files.forEach(row => {
      const tr = document.createElement('tr');
      tr.style.verticalAlign = 'middle';
      tr.style.textAlign = 'left';

      const td1 = document.createElement('td');
      td1.textContent = row['name'];
      tr.appendChild(td1);

      const td2 = document.createElement('td');
      td2.textContent = row['time'];
      tr.appendChild(td2);

      const td3 = document.createElement('td');
      td3.textContent = row['size'];
      tr.appendChild(td3);

      const td4 = document.createElement('td');
      const html1 = "<a href=\"{{ url_for('flow.get_flow_file', flow_id=flow_id, filename='0000') }}\" target=\"_blank\">下载</a>"
      const html2 = "<a href=\"{{ url_for('tools.code')}}?url={{ url_for('flow.get_flow_file', flow_id=flow_id, filename='0000', _external=True) }}\" target=\"_blank\">编辑</a>"
      const html3 = "<a onclick=\"return confirm('确定删除文件？')\" href=\"{{ url_for('flow.delete_flow_file', flow_id=flow_id, filename='0000') }}\">删除</a>"
      td4.innerHTML = html1.replace('0000', row['name']) + " | " + html2.replace('0000', row['name']) + " | " + html3.replace('0000', row['name']);
      if ({{ config.HOST_PORT }} !== 0){
        td4.innerHTML = td4.innerHTML.replace('http://sunjingyu.com', 'https://sunjingyu.com:{{ config.HOST_PORT }}').replace('http://www.sunjingyu.com', 'https://www.sunjingyu.com:{{ config.HOST_PORT }}')
      }
      tr.appendChild(td4);

      tableBody.appendChild(tr);
    });
  }

  function updateTextSolverStatus(solverStatus) {
    const textSolverStatus = document.getElementById('text_solver_status');
    textSolverStatus.innerText = '前处理状态：' + solverStatus;
  }

  function updateLog(logs) {
    const textarea = document.getElementById('textarea_log');
    textarea.value = logs;
    textarea.scrollTop = textarea.scrollHeight; // 滚动到最底部
  }

  function updateRunLog(run_logs) {
    const textarea = document.getElementById('textarea_run_log');
    textarea.value = run_logs;
    textarea.scrollTop = textarea.scrollHeight; // 滚动到最底部
  }

  function updateButtons(solverStatus) {
    const calculateBtn = document.getElementById('calculateBtn');
    const calculateLink = document.getElementById('calculateLink');
    // const resetBtn = document.getElementById('resetBtn');
    // const resetLink = document.getElementById('resetLink');

    if (solverStatus === 'Submitting' || solverStatus === 'Running' || solverStatus === 'Pause' || solverStatus === 'Stopping') {
      calculateBtn.style.display = 'inline';
      calculateLink.style.display = 'none';
    } else {
      calculateBtn.style.display = 'none';
      calculateLink.style.display = 'inline';
    }

    if (solverStatus === 'Completed' || solverStatus === 'Stopped' || solverStatus === 'Setting') {
      // resetBtn.style.display = 'none';
      // resetLink.style.display = 'inline';
    } else {
      // resetBtn.style.display = 'inline';
      // resetLink.style.display = 'none';
    }
  }

  function updateStatus() {
    if (isUpdate === true) {
      fetch("{{ url_for('flow.flow_status', flow_id=flow_id) }}")
        .then(response => response.json())
        .then(data => {
          console.log(data)
          updateButtons(data["flow_status"])
          updateLog(data['logs'])
          updateRunLog(data['run_logs'])
          updateTextSolverStatus(data["flow_status"])
          updateFiles(data["files"])
        })
        .catch(error => {
          console.error('Error:', error);
        });
    }
  }

  updateStatus()
  setInterval(updateStatus, 4000);

  $("[data-widget='collapse']").click()

</script>
{% endblock script %}

base/templates/flow/edit_flow.html
{% extends 'layout.html' %}
{% from 'bootstrap4/form.html' import render_form, render_form_row, render_field %}

{% block title %}编辑流程{% endblock title %}

{% block pageheader %}编辑流程{% endblock pageheader %}

{% block level %}
<li class="breadcrumb-item"><a href="/">主界面</a></li>
<li class="breadcrumb-item"><a href="{{ url_for('flow.manage_flows') }}">流程管理</a></li>
<li class="breadcrumb-item active">编辑流程</li>
{% endblock level %}

{% block content %}
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-6">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">流程详情</h3>
              </div>
              <div class="card-body">
                <form action="" method="post" class="form" role="form">
                  {{ render_form(form) }}
                </form>
              </div>
            </div>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
{% endblock content %}

{% block script %}
<script type="text/javascript">

  document.getElementById("flow").className = "nav-item menu-open"
  
</script>
{% endblock script %}