base/blueprints/sheet.py
# -*- coding: utf-8 -*-
"""

"""
import json
import os
import shutil

from flask import (Blueprint, abort, current_app, flash, jsonify, redirect, render_template, request, url_for)
from flask_login import current_user

from base.decorators import permission_required
from base.extensions import csrf
from base.utils.dir_status import create_id, sheets_detail

sheet_bp = Blueprint('sheet', __name__)


@sheet_bp.route('/create_sheet', methods=['GET', 'POST'])
@permission_required('SHEET')
def create_sheet():
    sheet_id = create_id(current_app.config['SHEET_PATH'])
    sheet_path = os.path.join(current_app.config['SHEET_PATH'], str(sheet_id))
    return render_template('sheet/create_sheet.html', sheet_id=sheet_id)


@sheet_bp.route('/edit_sheet/<int:sheet_id>', methods=['GET', 'POST'])
@permission_required('SHEET')
def edit_sheet(sheet_id):
    sheet_path = os.path.join(current_app.config['SHEET_PATH'], str(sheet_id))
    sheet_file = os.path.join(sheet_path, 'sheet.json')
    msg_file = os.path.join(sheet_path, 'sheet.msg')
    with open(msg_file, 'r', encoding='utf-8') as f:
        message = json.load(f)
    if os.path.exists(sheet_file):
        return render_template('sheet/edit_sheet.html', sheet_id=sheet_id, message=message)
    else:
        abort(404)


@sheet_bp.route('/view_sheet/<int:sheet_id>', methods=['GET'])
@permission_required('SHEET')
def view_sheet(sheet_id):
    sheet_path = os.path.join(current_app.config['SHEET_PATH'], str(sheet_id))
    sheet_file = os.path.join(sheet_path, 'sheet.json')
    msg_file = os.path.join(sheet_path, 'sheet.msg')
    with open(msg_file, 'r', encoding='utf-8') as f:
        message = json.load(f)
    if os.path.exists(sheet_file):
        return render_template('sheet/view_sheet.html', sheet_id=sheet_id, message=message)
    else:
        abort(404)


@sheet_bp.route('/upload/<int:sheet_id>', methods=['POST'])
@csrf.exempt
def upload(sheet_id):
    exceldata = request.form['exceldata']
    message = {}
    message['title'] = request.form['title']
    if not exceldata:
        res = {
            'success': 0,
            'message': '保存失败'
        }
    else:
        sheet_path = os.path.join(
            current_app.config['SHEET_PATH'], str(sheet_id))
        if not os.path.isdir(sheet_path):
            os.makedirs(sheet_path)
        try:
            sheet_file = os.path.join(sheet_path, 'sheet.json')
            with open(sheet_file, 'w', encoding='utf-8') as f:
                json.dump(exceldata, f, ensure_ascii=False)
            msg_file = os.path.join(sheet_path, 'sheet.msg')
            with open(msg_file, 'w', encoding='utf-8') as f:
                json.dump(message, f, ensure_ascii=False)
            res = {
                'success': 1,
                'message': '保存成功'
            }
        except:
            res = {
                'success': 0,
                'message': '保存失败'
            }
    return res


@sheet_bp.route('/read/<int:sheet_id>', methods=['POST'])
@csrf.exempt
def read(sheet_id):
    sheet_path = os.path.join(current_app.config['SHEET_PATH'], str(sheet_id))
    sheet_file = os.path.join(sheet_path, 'sheet.json')
    with open(sheet_file, 'r', encoding='utf-8') as f:
        exceldata = json.load(f)
    return exceldata


@sheet_bp.route('/sheets_status/')
@permission_required('SHEET')
def sheets_status():
    data = sheets_detail(current_app.config['SHEET_PATH'])
    return jsonify(data)


@sheet_bp.route('/manage_sheets/')
@permission_required('SHEET')
def manage_sheets():
    return render_template('sheet/manage_sheets.html')


@sheet_bp.route('/delete_sheet/<int:sheet_id>')
@permission_required('SHEET')
def delete_sheet(sheet_id):
    if not current_user.can('MODERATE'):
        flash('您的权限不能删除该数据表格！', 'warning')
        return redirect(url_for('.manage_sheets'))
    sheet_path = os.path.join(current_app.config['SHEET_PATH'], str(sheet_id))
    if os.path.exists(sheet_path):
        shutil.rmtree(sheet_path)
        flash('数据表格%s删除成功。' % sheet_id, 'success')
    else:
        flash('数据表格%s不存在！' % sheet_id, 'warning')
    return redirect(url_for('.manage_sheets'))

base/templates/sheet/create_sheet.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="csrf-token" content="{{ csrf_token() }}">
<title>新建数据表格</title>
<link type="image-icon" href="{{ url_for('static', filename='imgs/logo.svg') }}" rel="icon"/>

{% block css %}
{% if config.CDN %}
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/plugins/css/pluginsCss.css' />
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/plugins/plugins.css' />
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/css/luckysheet.css' />
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/assets/iconfont/iconfont.css' />
{% else %}
<link rel="stylesheet" href="{{ url_for('static', filename='luckysheet/plugins/css/pluginsCss.css') }}"/>
<link rel="stylesheet" href="{{ url_for('static', filename='luckysheet/plugins/plugins.css') }}"/>
<link rel="stylesheet" href="{{ url_for('static', filename='luckysheet/css/luckysheet.css') }}"/>
<link rel="stylesheet" href="{{ url_for('static', filename='luckysheet/assets/iconfont/iconfont.css') }}"/>
{% endif %}
{% endblock css %}
</head>

<body>
{% block content %}
<div id="luckysheet" style="margin:0px;padding:0px;position:absolute;width:100%;height:100%;left:0px;top:0px;"></div>
{% endblock content %}

{% block script %}
{% if config.CDN %}
<script src="https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/plugins/js/plugin.js"></script>
<script src="https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/luckysheet.umd.js"></script>
{% else %}
<script src="{{ url_for('static', filename='luckysheet/plugins/js/plugin.js') }}"></script>
<script src="{{ url_for('static', filename='luckysheet/luckysheet.umd.js') }}"></script>
{% endif %}

<script type="text/javascript">
  $(function () {
    var options = {
      container: "luckysheet",
      title: "标题",
      lang: "zh",
      myFolderUrl: "{{ url_for('sheet.manage_sheets') }}",
      functionButton: "<button class=\"btn btn-default\" onclick=\"uploadExcelData()\">保存</button> <a class=\"btn btn-default\" href=\"{{ url_for('.manage_sheets') }}\">返回</a>",
    }
    luckysheet.create(options)
  })

  function uploadExcelData() {
    $.post("{{ url_for('sheet.upload', sheet_id=sheet_id) }}", {
      exceldata: JSON.stringify(luckysheet.getAllSheets()),
      title: luckysheet.toJson().title
    }, function (data) {
      alert(data['message'])
      window.location.href="{{ url_for('sheet.edit_sheet', sheet_id=sheet_id) }}";
    });
  }

</script>
{% endblock script %}
</body>
</html>

base/templates/sheet/edit_sheet.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="csrf-token" content="{{ csrf_token() }}">
<title>编辑-{{ message['title'] }}</title>
<link type="image-icon" href="{{ url_for('static', filename='imgs/logo.svg') }}" rel="icon"/>

{% block css %}
{% if config.CDN %}
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/plugins/css/pluginsCss.css' />
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/plugins/plugins.css' />
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/css/luckysheet.css' />
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/assets/iconfont/iconfont.css' />
{% else %}
<link rel="stylesheet" href="{{ url_for('static', filename='luckysheet/plugins/css/pluginsCss.css') }}"/>
<link rel="stylesheet" href="{{ url_for('static', filename='luckysheet/plugins/plugins.css') }}"/>
<link rel="stylesheet" href="{{ url_for('static', filename='luckysheet/css/luckysheet.css') }}"/>
<link rel="stylesheet" href="{{ url_for('static', filename='luckysheet/assets/iconfont/iconfont.css') }}"/>
{% endif %}
{% endblock css %}
</head>

<body>
{% block content %}
<div id="luckysheet" style="margin:0px;padding:0px;position:absolute;width:100%;height:100%;left:0px;top:0px;"></div>
{% endblock content %}

{% block script %}
{% if config.CDN %}
<script src="https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/plugins/js/plugin.js"></script>
<script src="https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/luckysheet.umd.js"></script>
{% else %}
<script src="{{ url_for('static', filename='luckysheet/plugins/js/plugin.js') }}"></script>
<script src="{{ url_for('static', filename='luckysheet/luckysheet.umd.js') }}"></script>
{% endif %}

<script type="text/javascript">
  $(function () {
    var options = {
      container: "luckysheet",
      title: "{{ message['title'] }}",
      lang: "zh",
      myFolderUrl: "{{ url_for('sheet.manage_sheets') }}",
      loadUrl: "{{ url_for('sheet.read', sheet_id=sheet_id) }}",
      functionButton: "<button class=\"btn btn-default\" onclick=\"uploadExcelData()\">保存</button> <a class=\"btn btn-default\" href=\"{{ url_for('.view_sheet', sheet_id=sheet_id) }}\">查看</a>",
    }
    luckysheet.create(options)
  })

  function uploadExcelData() {
    $.post("{{ url_for('sheet.upload', sheet_id=sheet_id) }}", {
      exceldata: JSON.stringify(luckysheet.getAllSheets()),
      title: luckysheet.toJson().title
    }, function (data) {
      alert(data['message'])
    });
  }
</script>
{% endblock script %}
</body>
</html>

base/templates/sheet/manage_sheets.html
{% extends 'layout.html' %}
{% from 'bootstrap4/form.html' import render_form, render_form_row, render_field %}

{% block title %}数据表格管理{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='AdminLTE/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
{% endblock css %}

{% block pageheader %}数据表格管理{% endblock pageheader %}

{% block level %}
<li class="breadcrumb-item"><a href="/">主界面</a></li>
<li class="breadcrumb-item active">数据表格管理</li>
{% endblock level %}

{% block content %}
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">数据表格列表</h3>
              </div>
              <div class="card-body">
                <table id="data" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th width=50px>表格ID</th>
                      <th>标题</th>
                      <th width=150px>最新编辑时间</th>
                      <th width=150px>操作</th>
                    </tr>
                  </thead>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock content %}

{% block script %}

{% if config.CDN %}
<script src="{{ url_for('static', filename='AdminLTE/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ url_for('static', filename='AdminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
{% else %}
<script src="{{ url_for('static', filename='AdminLTE/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ url_for('static', filename='AdminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
{% endif %}

<script type="text/javascript">

  $.fn.dataTable.defaults.oLanguage = {
    "sProcessing": "处理中...",
    "sLengthMenu": "显示 _MENU_ 项结果",
    "sZeroRecords": "没有匹配结果",
    "sInfo": "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
    "sInfoEmpty": "显示第 0 至 0 项结果，共 0 项",
    "sInfoFiltered": "(由 _MAX_ 项结果过滤)",
    "sInfoPostFix": "",
    "sSearch": "搜索：",
    "sUrl": "",
    "sEmptyTable": "表中数据为空",
    "sLoadingRecords": "载入中...",
    "sInfoThousands": ",",
    "oPaginate": {
      "sFirst": "首页",
      "sPrevious": "上页",
      "sNext": "下页",
      "sLast": "末页"
    },
    "oAria": {
      "sSortAscending": ": 以升序排列此列",
      "sSortDescending": ": 以降序排列此列"
    }
  };

  $(function () {
    $('#data').DataTable({
      "paging": true,
      "pageLength": 50,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
      "ajax": "{{ url_for('sheet.sheets_status') }}",
      "columns": [
          { data: 'sheet_id' },
          { data: 'title' },
          { data: 'sheet_time' },
          { data: 'operation' },
      ],
    });
  });

  document.getElementById("sheets").className = "nav-item menu-open"
  document.getElementById("manage_sheets").className = "nav-link active"

</script>
{% endblock script %}

base/templates/sheet/view_sheet.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>查看-{{ message['title'] }}</title>
<link type="image-icon" href="{{ url_for('static', filename='imgs/logo.svg') }}" rel="icon"/>

{% block css %}
{% if config.CDN %}
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/plugins/css/pluginsCss.css' />
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/plugins/plugins.css' />
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/css/luckysheet.css' />
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/assets/iconfont/iconfont.css' />
{% else %}
<link rel="stylesheet" href="{{ url_for('static', filename='luckysheet/plugins/css/pluginsCss.css') }}"/>
<link rel="stylesheet" href="{{ url_for('static', filename='luckysheet/plugins/plugins.css') }}"/>
<link rel="stylesheet" href="{{ url_for('static', filename='luckysheet/css/luckysheet.css') }}"/>
<link rel="stylesheet" href="{{ url_for('static', filename='luckysheet/assets/iconfont/iconfont.css') }}"/>
{% endif %}
{% endblock css %}
</head>

<body>
{% block content %}
<div id="luckysheet" style="margin:0px;padding:0px;position:absolute;width:100%;height:100%;left:0px;top:0px;"></div>
{% endblock content %}

{% block script %}
{% if config.CDN %}
<script src="https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/plugins/js/plugin.js"></script>
<script src="https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/luckysheet.umd.js"></script>
{% else %}
<script src="{{ url_for('static', filename='luckysheet/plugins/js/plugin.js') }}"></script>
<script src="{{ url_for('static', filename='luckysheet/luckysheet.umd.js') }}"></script>
{% endif %}

<script type="text/javascript">
  $(function () {
    var options = {
      container: "luckysheet",
      title: "{{ message['title'] }}",
      lang: "zh",
      myFolderUrl: "{{ url_for('sheet.manage_sheets') }}",
      loadUrl: "{{ url_for('sheet.read', sheet_id=sheet_id) }}",
      allowCopy: false, // 是否允许拷贝
      showtoolbar: false, // 是否显示工具栏
      showsheetbar: false, // 是否显示底部sheet页按钮
      showstatisticBar: false, // 是否显示底部计数栏
      sheetBottomConfig: false, // sheet页下方的添加行按钮和回到顶部按钮配置
      allowEdit: false, // 是否允许前台编辑
      enableAddRow: false, // 允许增加行
      enableAddCol: false, // 允许增加列
      userInfo: false, // 右上角的用户信息展示样式
      showRowBar: false, // 是否显示行号区域
      showColumnBar: false, // 是否显示列号区域
      sheetFormulaBar: false, // 是否显示公式栏
      enableAddBackTop: false, // 返回头部按钮
      showstatisticBarConfig: {
        count:false,
        view:false,
        zoom:false,
      },
      showsheetbarConfig: {
        add: false, // 新增sheet
        menu: false, // sheet管理菜单
        sheet: false, // sheet页显示
      },
      hook: {
        cellMousedown:this.cellMousedown, // 绑定鼠标事件
      },
      forceCalculation: true, // 强制计算公式
    };
    luckysheet.create(options)
  })
</script>
{% endblock script %}
</body>
</html>